In [2]:
import pandas as pd

In [3]:
medical_df = pd.read_csv("medical_operations_dashboard_dataset.csv")
medical_df.head(10)

,patient_id,patient_name,age,gender,blood_group,city,state,contact_number,Admission_Id,Admission_Date,...,Shift,Bed_Id,Ward,Bed_Type,Bed_Status,Bill_Id,Total_Amount,Insurance_Coverage,Paid_Amount,Payment_Status
0,PAT100001,Advik Maharaj,94,Male,O+,Mumbai,Maharashtra,-6958682755,ADM100001,11/7/2025,...,Morning,BED2018,Ortho Ward,General,Cleaning,BILL100001,217621,217621,0,Paid
1,PAT100002,Isaac Dewan,13,Male,B+,Varanasi,Uttar Pradesh,-9831881973,ADM100002,8/15/2024,...,Morning,BED2016,Renal Ward,ICU,Available,BILL100002,137196,82317,54879,Pending
2,PAT100003,Caleb Sami,54,Male,O+,Surat,Gujarat,-6402417919,ADM100003,2/14/2025,...,Morning,BED2012,Ortho Ward,Semi-Private,Occupied,BILL100003,86579,77921,8658,Pending
3,PAT100004,Alexander Chander,64,Male,B+,Patna,Bihar,-8410529099,ADM100004,1/7/2025,...,Night,BED2050,General Ward,ICU,Occupied,BILL100004,15697,7848,7849,Pending
4,PAT100005,Jackson Tiwari,83,Male,B+,Kanpur,Uttar Pradesh,-7801823817,ADM100005,1/17/2026,...,Evening,BED2029,Gastro Ward,Private,Occupied,BILL100005,10976,10976,0,Paid
5,PAT100006,Hardik Saini,75,Male,O+,Coimbatore,Tamil Nadu,-9733616368,ADM100006,12/4/2025,...,Morning,BED2048,Pulmonary Ward,Private,Occupied,BILL100006,60495,30247,30248,Pending
6,PAT100007,Udarsh Mall,20,Male,B+,Bhopal,Madhya Pradesh,-7461364763,ADM100007,5/11/2026,...,Morning,BED2034,General Ward,Semi-Private,Cleaning,BILL100007,51781,51781,0,Paid
7,PAT100008,Gauri Sami,27,Female,A-,New Delhi,Delhi,-7445662494,ADM100008,9/29/2024,...,Morning,BED2033,Pulmonary Ward,ICU,Available,BILL100008,74987,67488,7499,Pending
8,PAT100009,Liam Dugal,48,Male,O+,Nagpur,Maharashtra,-9639960504,ADM100009,6/1/2025,...,Morning,BED2015,General Ward,Semi-Private,Occupied,BILL100009,28231,14115,14116,Pending
9,PAT100010,Pahal Chaudry,33,Female,B+,Jaipur,Rajasthan,-9134174069,ADM100010,8/18/2024,...,Morning,BED2015,General Ward,Semi-Private,Occupied,BILL100010,20463,14324,6139,Pending

In [5]:
medical_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          5000 non-null   str
 1   patient_name        5000 non-null   str
 2   age                 5000 non-null   int64
 3   gender              5000 non-null   str
 4   blood_group         5000 non-null   str
 5   city                5000 non-null   str
 6   state               5000 non-null   str
 7   contact_number      5000 non-null   int64
 8   Admission_Id        5000 non-null   str
 9   Admission_Date      5000 non-null   str
 10  Discharge_Date      3952 non-null   str
 11  Diagnosis           5000 non-null   str
 12  Treatment           5000 non-null   str
 13  Admission_status    5000 non-null   str
 14  Doctor_Id           5000 non-null   str
 15  Doctor_Name         5000 non-null   str
 16  Specialization      5000 non-null   str
 17  Department_Id       5000 non-null   str
 18  Department_Name     5000 non-null   str
 19  Staff_Id            5000 non-null   str
 20  Staff_Name          5000 non-null   str
 21  Role                5000 non-null   str
 22  Shift               5000 non-null   str
 23  Bed_Id              5000 non-null   str
 24  Ward                5000 non-null   str
 25  Bed_Type            5000 non-null   str
 26  Bed_Status          5000 non-null   str
 27  Bill_Id             5000 non-null   str
 28  Total_Amount        5000 non-null   int64
 29  Insurance_Coverage  5000 non-null   int64
 30  Paid_Amount         5000 non-null   int64
 31  Payment_Status      5000 non-null   str
dtypes: int64(5), str(27)
memory usage: 2.4 MB

## **Data Cleaning**

### **1.Changing str dates to datetime**

In [6]:
medical_df["Admission_Date"] = pd.to_datetime(
    medical_df["Admission_Date"],
    format="%m/%d/%Y"
)

In [8]:
medical_df[["Admission_Date"]].head()  #YYYY-MM-DD this is the date format

  Admission_Date
0     2025-11-07
1     2024-08-15
2     2025-02-14
3     2025-01-07
4     2026-01-17

In [9]:
medical_df["Discharge_Date"] = pd.to_datetime(
    medical_df["Discharge_Date"],
    format="%m/%d/%Y"
)

In [10]:
medical_df[["Discharge_Date"]].head()

  Discharge_Date
0            NaT
1     2024-08-18
2     2025-03-01
3            NaT
4            NaT

In [11]:
medical_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          5000 non-null   str
 1   patient_name        5000 non-null   str
 2   age                 5000 non-null   int64
 3   gender              5000 non-null   str
 4   blood_group         5000 non-null   str
 5   city                5000 non-null   str
 6   state               5000 non-null   str
 7   contact_number      5000 non-null   int64
 8   Admission_Id        5000 non-null   str
 9   Admission_Date      5000 non-null   datetime64[us]
 10  Discharge_Date      3952 non-null   datetime64[us]
 11  Diagnosis           5000 non-null   str
 12  Treatment           5000 non-null   str
 13  Admission_status    5000 non-null   str
 14  Doctor_Id           5000 non-null   str
 15  Doctor_Name         5000 non-null   str
 16  Specialization      5000 non-null   str
 17  Department_Id       5000 non-null   str
 18  Department_Name     5000 non-null   str
 19  Staff_Id            5000 non-null   str
 20  Staff_Name          5000 non-null   str
 21  Role                5000 non-null   str
 22  Shift               5000 non-null   str
 23  Bed_Id              5000 non-null   str
 24  Ward                5000 non-null   str
 25  Bed_Type            5000 non-null   str
 26  Bed_Status          5000 non-null   str
 27  Bill_Id             5000 non-null   str
 28  Total_Amount        5000 non-null   int64
 29  Insurance_Coverage  5000 non-null   int64
 30  Paid_Amount         5000 non-null   int64
 31  Payment_Status      5000 non-null   str
dtypes: datetime64[us](2), int64(5), str(25)
memory usage: 2.3 MB

### **2.Converting contact_number to a string**

In [12]:
medical_df["contact_number"] = medical_df["contact_number"].astype(str)

In [13]:
medical_df["contact_number"].dtype

### **3.Duplicate records**

In [14]:
medical_df.duplicated().sum()

np.int64(0)

### **4.Missing values**

In [15]:
medical_df.isnull().sum()

patient_id               0
patient_name             0
age                      0
gender                   0
blood_group              0
city                     0
state                    0
contact_number           0
Admission_Id             0
Admission_Date           0
Discharge_Date        1048
Diagnosis                0
Treatment                0
Admission_status         0
Doctor_Id                0
Doctor_Name              0
Specialization           0
Department_Id            0
Department_Name          0
Staff_Id                 0
Staff_Name               0
Role                     0
Shift                    0
Bed_Id                   0
Ward                     0
Bed_Type                 0
Bed_Status               0
Bill_Id                  0
Total_Amount             0
Insurance_Coverage       0
Paid_Amount              0
Payment_Status           0
dtype: int64

### **5.Age validation**

In [16]:
medical_df["age"].describe()

count    5000.000000
mean       47.735200
std        27.828862
min         0.000000
25%        23.000000
50%        49.000000
75%        72.000000
max        95.000000
Name: age, dtype: float64

### **6.Payment validation**

In [17]:
medical_df["Paid_Amount"] <= medical_df["Total_Amount"]

0       True
1       True
2       True
3       True
4       True
        ...
4995    True
4996    True
4997    True
4998    True
4999    True
Length: 5000, dtype: bool

In [21]:
(medical_df["Paid_Amount"] <= medical_df["Total_Amount"]).all()

np.True_

In [20]:
(medical_df["Insurance_Coverage"] + medical_df["Paid_Amount"] == medical_df["Total_Amount"]).all()

np.True_

In [24]:
medical_df.to_csv("medical_operations_dashboard_cleaned.csv", index=False)

In [25]:
cleaned_df = pd.read_csv("medical_operations_dashboard_cleaned.csv")

cleaned_df.head()

,patient_id,patient_name,age,gender,blood_group,city,state,contact_number,Admission_Id,Admission_Date,...,Shift,Bed_Id,Ward,Bed_Type,Bed_Status,Bill_Id,Total_Amount,Insurance_Coverage,Paid_Amount,Payment_Status
0,PAT100001,Advik Maharaj,94,Male,O+,Mumbai,Maharashtra,-6958682755,ADM100001,2025-11-07,...,Morning,BED2018,Ortho Ward,General,Cleaning,BILL100001,217621,217621,0,Paid
1,PAT100002,Isaac Dewan,13,Male,B+,Varanasi,Uttar Pradesh,-9831881973,ADM100002,2024-08-15,...,Morning,BED2016,Renal Ward,ICU,Available,BILL100002,137196,82317,54879,Pending
2,PAT100003,Caleb Sami,54,Male,O+,Surat,Gujarat,-6402417919,ADM100003,2025-02-14,...,Morning,BED2012,Ortho Ward,Semi-Private,Occupied,BILL100003,86579,77921,8658,Pending
3,PAT100004,Alexander Chander,64,Male,B+,Patna,Bihar,-8410529099,ADM100004,2025-01-07,...,Night,BED2050,General Ward,ICU,Occupied,BILL100004,15697,7848,7849,Pending
4,PAT100005,Jackson Tiwari,83,Male,B+,Kanpur,Uttar Pradesh,-7801823817,ADM100005,2026-01-17,...,Evening,BED2029,Gastro Ward,Private,Occupied,BILL100005,10976,10976,0,Paid